/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MaiAvatar {
        "img"?: string | null;
        "notifications"?: number | null;
        "username": string | null;
    }
    interface MaiButton {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMaiAvatarElement extends Components.MaiAvatar, HTMLStencilElement {
    }
    var HTMLMaiAvatarElement: {
        prototype: HTMLMaiAvatarElement;
        new (): HTMLMaiAvatarElement;
    };
    interface HTMLMaiButtonElement extends Components.MaiButton, HTMLStencilElement {
    }
    var HTMLMaiButtonElement: {
        prototype: HTMLMaiButtonElement;
        new (): HTMLMaiButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mai-avatar": HTMLMaiAvatarElement;
        "mai-button": HTMLMaiButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MaiAvatar {
        "img"?: string | null;
        "notifications"?: number | null;
        "username"?: string | null;
    }
    interface MaiButton {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mai-avatar": MaiAvatar;
        "mai-button": MaiButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mai-avatar": LocalJSX.MaiAvatar & JSXBase.HTMLAttributes<HTMLMaiAvatarElement>;
            "mai-button": LocalJSX.MaiButton & JSXBase.HTMLAttributes<HTMLMaiButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
